"""
This demo shows how to make a basic toolbar with some common controls.
"""

import wx
from wx_ribbon import FrameRibbon, themes, icons

# --- Make a basic wx app --
app = wx.App()
# make frame
frame = wx.Frame(
    parent=None,
    size=(1080, 720)
)
frame.Show()
frame.sizer = wx.BoxSizer(wx.VERTICAL)
frame.SetSizer(frame.sizer)
# make main panel
main = wx.Panel(frame, size=frame.GetSize())
main.sizer = wx.BoxSizer(wx.VERTICAL)
main.SetSizer(main.sizer)
frame.sizer.Add(main, proportion=1, flag=wx.EXPAND)

# --- Make the ribbon ---
# add ribbon
ribbon = FrameRibbon(
    main, 
    theme=themes.RB_THEME_LIGHT  # use RB_THEME_DARK for dark mode, or create your own theme by subclassing themes.BaseTheme!
)
main.sizer.Add(ribbon, flag=wx.EXPAND)

# add a "File" section with some common controls
ribbon.AddSection(
    name="file",
    label="File",
    icon=icons.RB_ICON_FILE_OPEN
)
ribbon.AddButton(
    section="file",
    name="file_new",
    label="New",
    icon=icons.RB_ICON_FILE_NEW
)
ribbon.AddButton(
    section="file",
    name="file_save",
    label="Save",
    icon=icons.RB_ICON_FILE_SAVE
)
ribbon.AddButton(
    section="file",
    name="file_open",
    label="Open",
    icon=icons.RB_ICON_FILE_OPEN
)
ribbon.AddSeparator()

# add an "Edit" section with some common controls
ribbon.AddSection(
    name="edit",
    label="Edit",
    icon=icons.RB_ICON_EDIT
)
ribbon.AddButton(
    section="edit",
    name="copy",
    label="Copy",
    icon=icons.RB_ICON_COPY
)
ribbon.AddButton(
    section="edit",
    name="copy",
    label="Copy",
    icon=icons.RB_ICON_PASTE
)
ribbon.AddButton(
    section="edit",
    name="undo",
    label="Undo",
    icon=icons.RB_ICON_UNDO
)
ribbon.AddButton(
    section="edit",
    name="undo",
    label="Redo",
    icon=icons.RB_ICON_REDO
)

# add section for editing the current project
ribbon.AddSeparator()
ribbon.AddSection(
    name="project",
    label="Project",
    icon=icons.RB_ICON_INFO
)
ribbon.AddButton(
    section="project",
    name="settings",
    label="Settings", 
    icon=icons.RB_ICON_SETTINGS
)
def project_callback(evt=None):
    """
    Function called when the project button is clicked on. Just links you to this project on GitHub.

    Parameters
    ----------
    evt : wx.ButtonEvent, optional
        Event generated by the button.
    """
    import webbrowser
    webbrowser.open("https://github.com/TEParsons/wx-ribbon")
ribbon.AddButton(
    section="project",
    name="info",
    label="TEParsons/wx-ribbon", 
    icon=icons.RB_ICON_INFO, 
    callback=project_callback,
    style=wx.BU_LEFT  # this button has a label!
)

# add section for running stuff to show off the switch ctrl
ribbon.AddSeparator()
ribbon.AddSection(
    name="run",
    label="Run",
    icon=icons.RB_ICON_PLAY
)
switch = ribbon.AddSwitchCtrl(
    section="run",
    name="mode",
    labels=("Run", "Debug"), 
    startMode=0,
    style=wx.HORIZONTAL
)
run = ribbon.AddButton(
    section="run",
    name="run",
    label="Run",
    icon=icons.RB_ICON_PLAY
)
switch.AddDependant(run, 0, action="enable")  # adding buttons as "dependents" to a switch ctrl will enable/disable them according to its state
debug = ribbon.AddButton(
    section="run",
    name="debug",
    label="Debug",
    icon=icons.RB_ICON_BUG
)
switch.AddDependant(debug, 1, action="enable")

# add section for user switching control - this one doesn't have a label, and is off to the right
ribbon.AddSeparator()
ribbon.AddStretchSpacer()
ribbon.AddSection(
    name="user",
)
def user_callback(evt=None):
    """
    Function called when the user control is clicked on. Just links you to my GitHub.

    Parameters
    ----------
    evt : wx.ButtonEvent, optional
        Event generated by the button.
    """
    import webbrowser
    webbrowser.open("https://github.com/TEParsons")
# we need to create a menu for the dropdown to open when clicked...
user_menu = wx.Menu()
for lbl in ("Switch user...", "Log out"):
    user_menu.Append(wx.ID_ANY, item=lbl)
ribbon.AddDropdownButton(
    section="user",
    name="user",
    label="TEParsons", 
    icon=icons.RB_ICON_USER, 
    callback=user_callback, 
    menu=user_menu
)

# --- Finish up and start the app ---
# add panel
panel = wx.Panel(main)
main.sizer.Add(panel, proportion=1, flag=wx.EXPAND)
# layout
main.Layout()

# start
app.MainLoop()

